# Generated by Django 2.2.10 on 2020-04-27 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agro', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('news_name', models.CharField(max_length=50)),
                ('news_image', models.ImageField(upload_to='pics')),
                ('news_date', models.DateField()),
                ('news_description', models.TextField()),
            ],
        ),
    ]
