# Generated by Django 2.2.10 on 2020-04-27 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agro', '0002_news'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='news_hidden_text',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
