# Generated by Django 2.2.10 on 2020-04-27 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agro', '0003_news_news_hidden_text'),
    ]

    operations = [
        migrations.CreateModel(
            name='Plantation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plantation_name', models.CharField(max_length=50)),
                ('plantation_image', models.ImageField(upload_to='pics')),
            ],
        ),
    ]
