# Generated by Django 2.2.10 on 2020-04-27 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agro', '0004_plantation'),
    ]

    operations = [
        migrations.CreateModel(
            name='Teams',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_name', models.CharField(max_length=50)),
                ('team_image', models.ImageField(upload_to='pics')),
                ('team_role', models.CharField(max_length=50)),
            ],
        ),
    ]
