# Generated by Django 2.2.10 on 2020-05-02 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agro', '0008_auto_20200428_0310'),
    ]

    operations = [
        migrations.AddField(
            model_name='labour',
            name='farmer_id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tasks',
            name='farmer_id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
